apiVersion: apps/v1
kind: Deployment
metadata:
  name: test001
  labels:
    app: test001
  namespace: namespace-workflow-1683647023374
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test001
  template:
    metadata:
      labels:
        app: test001
    spec:
      containers:
        - name: test001
          image: acrworkflow1683647023374.azurecr.io/image-workflow-1683647023374:latest
          ports:
            - containerPort: 3000