apiVersion: apps/v1
kind: Deployment
metadata:
  name: test0314-001
  labels:
    app: test0314-001
  namespace: namespace-workflow-1678806186133
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test0314-001
  template:
    metadata:
      labels:
        app: test0314-001
    spec:
      containers:
        - name: test0314-001
          image: acrworkflow1678806186133.azurecr.io/image-workflow-1678806186133:latest
          ports:
            - containerPort: 80