apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-test-2
  labels:
    app: express-test-2
  namespace: namespace-workflow-1679345166421
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-test-2
  template:
    metadata:
      labels:
        app: express-test-2
    spec:
      containers:
        - name: express-test-2
          image: acrworkflow1679345166421.azurecr.io/image-workflow-1679345166421:latest
          ports:
            - containerPort: 80