apiVersion: apps/v1
kind: Deployment
metadata:
  name: test0313-001
  labels:
    app: test0313-001
  namespace: namespace-workflow-1678729578638
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test0313-001
  template:
    metadata:
      labels:
        app: test0313-001
    spec:
      containers:
        - name: test0313-001
          image: acrworkflow1678729578638.azurecr.io/image-workflow-1678729578638:latest
          ports:
            - containerPort: 80