apiVersion: apps/v1
kind: Deployment
metadata:
  name: test011
  labels:
    app: test011
  namespace: namespace-workflow-1678809032108
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test011
  template:
    metadata:
      labels:
        app: test011
    spec:
      containers:
        - name: test011
          image: acrworkflow1678809032108.azurecr.io/image-workflow-1678809032108:latest
          ports:
            - containerPort: 80