apiVersion: apps/v1
kind: Deployment
metadata:
  name: test0327-001
  labels:
    app: test0327-001
  namespace: namespace-workflow-1679951580246
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test0327-001
  template:
    metadata:
      labels:
        app: test0327-001
    spec:
      containers:
        - name: test0327-001
          image: acrworkflow1679951580246.azurecr.io/image-workflow-1679951580246:latest
          ports:
            - containerPort: 80