apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp0313-001
  labels:
    app: testapp0313-001
  namespace: namespace-workflow-1678732933100
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp0313-001
  template:
    metadata:
      labels:
        app: testapp0313-001
    spec:
      containers:
        - name: testapp0313-001
          image: acrworkflow1678732933100.azurecr.io/image-workflow-1678732933100:latest
          ports:
            - containerPort: 80