apiVersion: apps/v1
kind: Deployment
metadata:
  name: test111
  labels:
    app: test111
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test111
  template:
    metadata:
      labels:
        app: test111
    spec:
      containers:
        - name: test111
          image: acrworkflow1680494703488.azurecr.io/image-workflow-1684268562303:latest
          ports:
            - containerPort: 3000