apiVersion: v1
kind: Service
metadata:
  name: express-test
  namespace: namespace-workflow-1679343994908
spec:
  type: LoadBalancer
  selector:
    app: express-test
  ports:
    - protocol: TCP
      port: 1313
      targetPort: 1313