apiVersion: v1
kind: Service
metadata:
  name: test0314-001
  namespace: namespace-workflow-1678806186133
spec:
  type: LoadBalancer
  selector:
    app: test0314-001
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80