apiVersion: v1
kind: Service
metadata:
  name: express-test
  namespace: namespace-workflow-1679339679795
spec:
  type: LoadBalancer
  selector:
    app: express-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80